controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - shoulder_joint
      - elbow_joint
      - forearm_joint
      - wrist_pitch_joint
      - wrist_roll_joint
      - left_finger_joint
      - right_finger_joint

    command_interfaces: [position]
    state_interfaces: [position, velocity]
    gains:
      shoulder_joint: {p: 300.0, d: 10.0, i: 0.0}
      elbow_joint:    {p: 300.0, d: 10.0, i: 0.0}
      forearm_joint:  {p: 300.0, d: 10.0, i: 0.0}
      wrist_pitch_joint:  {p: 120.0, d: 6.0,  i: 0.0}
      wrist_roll_joint:   {p: 80.0,  d: 4.0,  i: 0.0}
      left_finger_joint:  {p: 50.0, d: 2.0, i: 0.0}
      right_finger_joint: {p: 50.0, d: 2.0, i: 0.0}